spring:
  aop:
    proxy-target-class: true

  datasource:
    continue-on-error: true
    initialize: false

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        cache:
          use_second_level_cache: false

  batch:
    initializer:
      enabled: false

logging:
  level:
    org.oagi.srt: INFO
    org.springframework: INFO
    org.hibernate.SQL: INFO