# AOP
spring:
  aop:
    proxy-target-class: true

# DataSource
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:hsql://docker/oagi
    username: oagi
    password: oagi

    continue-on-error: true
    initialize: false
    auto-commit: false

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
#        globally_quoted_identifiers: true
        id:
          new_generator_mappings: true
        cache:
          use_second_level_cache: false
        ejb:
          interceptor: org.oagi.srt.persistence.populate.EntityUpdateInterceptor

  batch:
    initializer:
      enabled: false

logging:
  level:
    org.oagi.srt: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: INFO

# Staging environment
---
spring:
  profiles: staging

# DataSource
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/OAGISRTDB
    username: oagi
    password: oagi
    platform: oracle
    auto-commit: false