# AOP
spring:
  aop:
    proxy-target-class: true

# DataSource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://docker:3306/oagsrt_revision?rewriteBatchedStatements=true&useCompression=true&allowMultiQueries=true
    username: root
    password: qwer1234
    platform: mysql

#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@docker:1521/xe
#    username: oagi
#    password: oagi
#    platform: oracle

    continue-on-error: true
    initialize: false

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true

  batch:
    initializer:
      enabled: false

logging:
  level:
    org.oagi.srt: INFO
    org.springframework: INFO
    org.hibernate.SQL: INFO

# Staging environment
---
spring:
  profiles: staging

# DataSource
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/OAGISRTDB
    username: oagi
    password: oagi
    platform: oracle